---
- name: Set Windows preferences
  hosts: windows

  tasks:
  - name: "combine taskbar buttons: never"
    # 0 = Always combine, hide labels
    # 1 = Combine when taskbar is full
    # 2 = Never combine
    win_regedit:
      path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
      name: TaskbarGlomLevel
      data: 2
      type: dword

  - name: Restart Windows Explorer
    win_shell: Stop-Process -ProcessName explorer
  